Name:           ros-hydro-ir-trans-drivers
Version:        0.0.4
Release:        3%{?dist}
Summary:        ROS ir_trans_drivers package

Group:          Development/Libraries
License:        Binary Only
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-hydro-catkin
BuildRequires:  cmake

%description
irtrans drivers third party code for Maggie robot

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Fri Sep 18 2015 Social Robots <social.robots@uc3m.es> - 0.0.4-3
- Autogenerated by Bloom

* Thu Sep 10 2015 Social Robots <social.robots@uc3m.es> - 0.0.4-2
- Autogenerated by Bloom

* Thu Sep 10 2015 Social Robots <social.robots@uc3m.es> - 0.0.4-1
- Autogenerated by Bloom

* Tue Sep 08 2015 Social Robots <social.robots@uc3m.es> - 0.0.4-0
- Autogenerated by Bloom

* Tue Sep 08 2015 Social Robots <social.robots@uc3m.es> - 0.0.2-1
- Autogenerated by Bloom

